#include "OBJExporter.h"
#include "Mesh.h"
#include <fstream>
#include <iostream>

bool OBJExporter::exportToFile(const std::string& filename, const Mesh& mesh) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Cannot create file: " << filename << std::endl;
        return false;
    }

    const auto& vertices = mesh.getVertices();
    const auto& triangles = mesh.getTriangles();

    file << "# Wavefront OBJ file\n";
    file << "# Generated by DepthMapConverter\n\n";
    file << "o DepthMapMesh\n\n";

    // Write vertices
    for (const auto& v : vertices) {
        file << "v " << v.position.x << " " << v.position.y << " " << v.position.z << "\n";
    }
    file << "\n";

    // Write normals
    for (const auto& v : vertices) {
        file << "vn " << v.normal.x << " " << v.normal.y << " " << v.normal.z << "\n";
    }
    file << "\n";

    // Write faces (OBJ indices start at 1, not 0)
    for (const auto& t : triangles) {
        file << "f "
             << (t.indices[0] + 1) << "//" << (t.indices[0] + 1) << " "
             << (t.indices[1] + 1) << "//" << (t.indices[1] + 1) << " "
             << (t.indices[2] + 1) << "//" << (t.indices[2] + 1) << "\n";
    }

    file.close();
    std::cout << "Exported to " << filename << " (Wavefront OBJ format)" << std::endl;
    return true;
}